import { CommonModule } from '@angular/common';
import { Component, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../core/auth.service';
import { BiometricCameraComponent } from '../core/biometric-camera.component';
import { FaceService } from '../core/face.service';
import { SupabaseService } from '../core/supabase.service';

@Component({ standalone: true, imports: [FormsModule, RouterLink], template: `<main class="auth"><h1>Asistencia Biométrica</h1><p>Configure el primer administrador institucional.</p><form (ngSubmit)="submit()"><input [(ngModel)]="fullName" name="name" placeholder="Nombre completo" required><input [(ngModel)]="email" name="email" type="email" placeholder="Correo institucional" required><input [(ngModel)]="password" name="password" type="password" minlength="10" placeholder="Contraseña (mínimo 10)" required><button>Crear administrador</button></form><p class="feedback">{{message()}}</p><a routerLink="/login">Ya tengo una cuenta</a></main>` })
export class SetupPage { fullName = ''; email = ''; password = ''; message = signal(''); constructor(private sb: SupabaseService, private r: Router) {} async submit() { try { const data = await this.sb.invokePublicFunction('setup-admin', { full_name: this.fullName, email: this.email, password: this.password }); this.message.set(data?.message || 'Administrador creado.'); this.r.navigateByUrl('/login'); } catch (error) { this.message.set(error instanceof Error ? error.message : 'No se pudo crear el administrador.'); } } }

@Component({ standalone: true, imports: [CommonModule, FormsModule, RouterLink], template: `<main class="auth"><h1>Ingresar</h1><p>Accede al control de asistencia biométrica.</p><form (ngSubmit)="submit()"><input [(ngModel)]="email" name="email" type="email" required placeholder="Correo"><input [(ngModel)]="password" name="password" type="password" required placeholder="Contraseña"><button>Iniciar sesión</button></form><p class="feedback error" *ngIf="message()">{{message()}}</p><a routerLink="/setup">Primera instalación</a></main>` })
export class LoginPage { email = ''; password = ''; message = signal(''); constructor(private a: AuthService, private r: Router) {} async submit() { try { await this.a.login(this.email, this.password); await this.r.navigateByUrl('/dashboard'); } catch (e) { this.message.set(e instanceof Error ? e.message : 'No se pudo iniciar sesión'); } } }

@Component({ standalone: true, imports: [RouterLink], template: `<main><section class="welcome-card"><span class="eyebrow">Sistema de control académico</span><h1>Bienvenido</h1><p>Registre alumnos mediante reconocimiento facial y controle la asistencia de forma rápida. Las fotos no se almacenan: solo se guardan plantillas biométricas cifradas.</p></section><section class="dashboard-grid"><a class="dashboard-card" routerLink="/alumnos/nuevo"><span class="card-icon">👨‍🎓</span><h2>Registrar alumno</h2><p>Complete sus datos y capture tres muestras faciales.</p></a><a class="dashboard-card" routerLink="/asistencia"><span class="card-icon">📷</span><h2>Marcar asistencia</h2><p>Reconozca al alumno y registre su entrada o salida.</p></a><a class="dashboard-card" routerLink="/reportes"><span class="card-icon">📊</span><h2>Reportes</h2><p>Consulte asistencias y faltas por fecha.</p></a><a class="dashboard-card" routerLink="/alumnos"><span class="card-icon">🧑‍🤝‍🧑</span><h2>Lista de alumnos</h2><p>Revise, edite y gestione los registros existentes.</p></a></section></main>` })
export class DashboardPage {}

@Component({ standalone: true, imports: [CommonModule, RouterLink], template: `<main><div class="page-heading"><div><span class="eyebrow">Gestión académica</span><h1>Lista de alumnos</h1><p>Seleccione un alumno para editar sus datos o actualizar su plantilla facial.</p></div><a class="button" routerLink="/alumnos/nuevo">+ Registrar alumno</a></div><p class="feedback" *ngIf="message()">{{message()}}</p><section class="table-card"><table><thead><tr><th>Documento</th><th>Apellidos y nombres</th><th>Estado</th><th></th></tr></thead><tbody><tr *ngFor="let s of students()"><td>{{s.document_number}}</td><td><strong>{{s.last_names}}, {{s.first_names}}</strong><small *ngIf="s.email">{{s.email}}</small></td><td><span class="badge success">{{s.status}}</span></td><td><a class="text-link" [routerLink]="['/alumnos',s.id]">Editar</a></td></tr><tr *ngIf="!students().length && !message()"><td colspan="4">Aún no hay alumnos registrados.</td></tr></tbody></table></section></main>` })
export class StudentsPage { students = signal<any[]>([]); message = signal('Cargando…'); constructor(private sb: SupabaseService) { this.load(); } async load() { const { data, error } = await this.sb.client.from('students').select('*').order('last_names'); this.students.set(data || []); this.message.set(error?.message || ''); } }

@Component({ standalone: true, imports: [CommonModule, FormsModule, BiometricCameraComponent], template: `<main><div class="page-heading"><div><span class="eyebrow">Enrolamiento biométrico</span><h1>{{id ? 'Editar alumno' : 'Registrar alumno'}}</h1><p>Registre los datos y luego capture tres muestras del rostro.</p></div></div><section class="enrollment-grid"><form class="form-card" (ngSubmit)="save()"><h2>Datos del alumno</h2><label>Documento<input [(ngModel)]="student.document_number" name="doc" required></label><label>Nombres<input [(ngModel)]="student.first_names" name="names" required></label><label>Apellidos<input [(ngModel)]="student.last_names" name="last" required></label><label>Correo (opcional)<input [(ngModel)]="student.email" name="email" type="email"></label><button>Guardar datos</button><p class="feedback">{{message()}}</p></form><section class="camera-card"><div class="step-count"><span [class.done]="samples.length >= 1">1</span><i></i><span [class.done]="samples.length >= 2">2</span><i></i><span [class.done]="samples.length >= 3">3</span></div><p *ngIf="!savedId" class="hint">Guarde primero los datos para habilitar la cámara.</p><app-biometric-camera *ngIf="savedId" title="Capturar rostro" (descriptor)="sample($event)"/><button *ngIf="savedId && samples.length" [disabled]="samples.length < 3" (click)="enroll()">Guardar plantilla ({{samples.length}}/3 muestras)</button><p *ngIf="savedId && samples.length < 3" class="hint">Capture {{3 - samples.length}} muestra(s) más para completar el enrolamiento.</p></section></section></main>` })
export class StudentFormPage { id = ''; savedId = ''; student: any = { status: 'activo' }; samples: number[][] = []; message = signal(''); constructor(private sb: SupabaseService, private face: FaceService, private r: Router) { const routeId = this.r.url.split('/').pop() || ''; this.id = routeId === 'nuevo' ? '' : routeId; this.savedId = this.id; if (this.id) this.load(); } async load() { const { data } = await this.sb.client.from('students').select('*').eq('id', this.id).single(); if (data) this.student = data; } async save() { const q = this.savedId ? this.sb.client.from('students').update(this.student).eq('id', this.savedId) : this.sb.client.from('students').insert(this.student).select().single(); const { data, error } = await q as any; if (error) this.message.set(error.message); else { this.savedId = this.savedId || data.id; this.message.set('Datos guardados. Capture tres muestras faciales.'); } } sample(d: number[]) { if (this.samples.length < 3) this.samples.push(d); this.message.set(`Muestra ${this.samples.length} de 3 capturada correctamente.`); } async enroll() { try { await this.sb.invokeAuthenticatedFunction('enroll-biometric', { student_id: this.savedId, descriptor: this.face.average(this.samples), sample_count: this.samples.length }); this.samples = []; this.message.set('Plantilla biométrica cifrada y guardada correctamente.'); } catch (error) { this.message.set(error instanceof Error ? error.message : 'No se pudo guardar la plantilla.'); } } }

@Component({ standalone: true, imports: [BiometricCameraComponent], template: `<main><div class="page-heading"><div><span class="eyebrow">Reconocimiento en vivo</span><h1>Marcar asistencia</h1><p>Colóquese frente a la cámara; capture el rostro para registrar entrada o salida.</p></div></div><section class="attendance-card"><app-biometric-camera title="Marcado de asistencia en tiempo real" (descriptor)="recognize($event)"/><div class="recognition-status" [class.has-error]="error()"><strong>{{statusTitle()}}</strong><p>{{message() || 'La cámara procesará el rostro localmente antes de consultar la plantilla cifrada.'}}</p></div></section></main>` })
export class AttendancePage { message = signal(''); error = signal(false); statusTitle = computed(() => this.error() ? 'No se pudo reconocer' : this.message() ? 'Resultado del marcado' : 'Listo para reconocer'); constructor(private sb: SupabaseService) {} async recognize(descriptor: number[]) { this.error.set(false); this.message.set('Verificando identidad…'); try { const data = await this.sb.invokeAuthenticatedFunction('recognize-attendance', { descriptor, liveness_passed: true }); this.message.set(data?.message || `${data?.student_name}: ${data?.status}`); } catch (error) { this.error.set(true); this.message.set(error instanceof Error ? error.message : 'No se pudo verificar la asistencia.'); } } }

@Component({ standalone: true, imports: [CommonModule, FormsModule], template: `<main><div class="page-heading"><div><span class="eyebrow">Control diario</span><h1>Reporte de asistencia</h1><p>Consulta la asistencia y faltas de todos los alumnos activos.</p></div></div><section class="report-toolbar"><label>Fecha<input type="date" [(ngModel)]="date" (change)="load()"></label><button (click)="load()">Consultar</button></section><section class="summary-grid"><article><span>Total alumnos</span><strong>{{students().length}}</strong></article><article><span>Asistieron</span><strong>{{attended()}}</strong></article><article><span>Faltas</span><strong>{{students().length - attended()}}</strong></article></section><p class="feedback" *ngIf="message()">{{message()}}</p><section class="table-card"><table><thead><tr><th>Documento</th><th>Apellidos y nombres</th><th>Hora de entrada</th><th>Hora de salida</th><th>Estado</th></tr></thead><tbody><tr *ngFor="let row of rows()"><td>{{row.student.document_number}}</td><td>{{row.student.last_names}}, {{row.student.first_names}}</td><td>{{row.entry}}</td><td>{{row.exit}}</td><td><span class="badge" [class.success]="row.attendance" [class.danger]="!row.attendance">{{row.attendance ? 'Asistió' : 'Falta'}}</span></td></tr></tbody></table></section></main>` })
export class ReportsPage { date = new Date().toISOString().slice(0, 10); students = signal<any[]>([]); rows = signal<any[]>([]); message = signal(''); attended = computed(() => this.rows().filter(row => row.attendance).length); constructor(private sb: SupabaseService) { this.load(); } async load() { this.message.set('Cargando reporte…'); const [{ data: students, error: studentsError }, { data: attendance, error: attendanceError }] = await Promise.all([this.sb.client.from('students').select('*').eq('status', 'activo').order('last_names'), this.sb.client.from('attendance').select('*').eq('attendance_date', this.date)]); if (studentsError || attendanceError) { this.message.set(studentsError?.message || attendanceError?.message || 'No se pudo cargar el reporte.'); return; } const byStudent = new Map((attendance || []).map((item: any) => [item.student_id, item])); this.students.set(students || []); this.rows.set((students || []).map((student: any) => { const record: any = byStudent.get(student.id); return { student, attendance: record, entry: record?.entry_at ? new Date(record.entry_at).toLocaleTimeString('es-PE', { hour: '2-digit', minute: '2-digit' }) : '—', exit: record?.exit_at ? new Date(record.exit_at).toLocaleTimeString('es-PE', { hour: '2-digit', minute: '2-digit' }) : '—' }; })); this.message.set(''); } }

@Component({ standalone: true, template: `<main><h1>{{title}}</h1><p>Módulo disponible para usuarios autorizados.</p></main>` })
export class PlaceholderPage { title = 'Módulo'; }
